# -*- coding: utf-8 -*-
"""worksheet1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfJbrixBrDe6F4iHeuFhDTdE5Ic8178T
"""

# Question no1
x = 24

if x % 24 == 0:
    print(x,"Is Even Number")
else:
    print(x, "Is Odd Number")

# Question no2
age = int(input("Enter your age: "))

if age < 18:
    print(age, "is categorized as Minor")
elif 18 <= age < 65:
    print(age, "is categorized as Adult")
else:
    print(age, "is categorized as Senior")

# Question no3

temp = float(input("Enter the temperature in Celsius: "))

if temp > 30:
    print(temp, "°C is Hot")
elif 15 <= temp <= 30:
    print(temp, "°C is Warm")
else:
    print(temp, "°C is Cold")

# Question no4

score = int(input("Enter the score: "))

if 90 <= score <= 100:
    print(score, "is Grade A")
elif 80 <= score < 90:
    print(score, "is Grade B")
elif 70 <= score < 80:
    print(score, "is Grade C")
elif 60 <= score < 70:
    print(score, "is Grade D")
else:
    print(score, "is Grade F")

# Question no5

numbers = list(map(int, input("Enter numbers separated by spaces: ").split()))
total = sum(numbers)

print("The sum of the list is:", total)

# Question no6

n = int(input("Enter a number: "))

print("The first 10 multiples of", n, "are:")
for i in range(1, 11):
    print(n * i)

# Question no7

s = input("Enter a string: ")

print("The reverse of the string is:", s[::-1])

# Question no8

string = input("Enter a string: ")
vowels = "aeiouAEIOU"
count = 0

for char in string:
    if char in vowels:
        count += 1

print("The number of vowels in the string is:", count)

# Question no9

n = int(input("Enter a number to start countdown: "))

while n > 0:
    print(n)
    n -= 1

# Question no10

import random

correct_number = random.randint(1, 100)
guess = None

while guess != correct_number:
    guess = int(input("Guess the number (between 1 and 100): "))

    if guess < correct_number:
        print("Too low!")
    elif guess > correct_number:
        print("Too high!")
    else:
        print("Congratulations! You guessed it right!")

# Question no11

num = int(input("Enter a number to calculate factorial: "))
factorial = 1
i = 1

while i <= num:
    factorial *= i
    i += 1

print("The factorial of", num, "is:", factorial)

# Question no12

n = int(input("Enter how many numbers you want in Fibonacci sequence: "))
a, b = 0, 1
count = 0

while count < n:
    print(a, end=' ')
    a, b = b, a + b
    count += 1

# Question no13

string = input("Enter a string: ")
print("The string in uppercase is:", string.upper())

# Question no14

num = int(input("Enter a number to find its square: "))
print("The square of", num, "is:", num ** 2)

# Question no15

string = input("Enter a string: ")

if string == string[::-1]:
    print(string, "is a palindrome")
else:
    print(string, "is not a palindrome")

# Question no16

numbers = list(map(int, input("Enter numbers separated by spaces: ").split()))
print("The maximum number in the list is:", max(numbers))